### ISSUE TITLE
Dependencies mismatch pypi.org version capability

### ISSUE THREAD

**Issue by phelanma** [diogomatoschaves/stratestic#14]
Expectation:
https://pypi.org/project/stratestic/
Says the package is compatible with Python 3.12.

Problem:
stratestic dependency numba-0.56.2 is not compatible with Python 3.12

 - Thanks for the effort though!

Log Reference
```
Collecting numba==0.56.2 (from stratestic==1.6.0->-r requirements.txt (line 21))
  Using cached numba-0.56.2.tar.gz (2.4 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      /private/var/folders/7n/t3k_lsl515bf7cbfwqg01n_c0000gn/T/pip-install-ki9c7a9v/numba_6bd1a137509f445ca54303d8beaa48b8/versioneer.py:335: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/7n/t3k_lsl515bf7cbfwqg01n_c0000gn/T/pip-install-ki9c7a9v/numba_6bd1a137509f445ca54303d8beaa48b8/setup.py", line 51, in <module>
          _guard_py_ver()
        File "/private/var/folders/7n/t3k_lsl515bf7cbfwqg01n_c0000gn/T/pip-install-ki9c7a9v/numba_6bd1a137509f445ca54303d8beaa48b8/setup.py", line 48, in _guard_py_ver
          raise RuntimeError(msg.format(cur_py, min_py, max_py))
      RuntimeError: Cannot install on Python version 3.12.2; only versions >=3.7,<3.11 are supported.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

**Comment by diogomatoschaves** [comment]
Noted, thanks for reporting that 👌

**Comment by AndreyRzhaksinskiy** [comment]
Hi,
the same issue
```
Collecting numba==0.56.2 (from stratestic)
  Using cached numba-0.56.2.tar.gz (2.4 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\I344088\AppData\Local\Temp\pip-install-d5wlnd1v\numba_8d65ba100c6d4841899d159811d08173\setup.py", line 51, in <module>
          _guard_py_ver()
        File "C:\Users\I344088\AppData\Local\Temp\pip-install-d5wlnd1v\numba_8d65ba100c6d4841899d159811d08173\setup.py", line 48, in _guard_py_ver
          raise RuntimeError(msg.format(cur_py, min_py, max_py))
      RuntimeError: Cannot install on Python version 3.11.7; only versions >=3.7,<3.11 are supported.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
Is it possible to fix compatibility with latest Python version?
Thank you for a good library.

**Comment by diogomatoschaves** [comment]
@phelanma @AndreyRzhaksinskiy I have updated the project to only allow python versions >=3.8 and <3.11. Allowing it to higher python versions will create a lot of problems with dependencies, so for the moment it will have to be like this. Please update your projects to use a compatible python version.
